#!/usr/bin/env python3
from pathlib import Path

# Second commit intentionally triggers the workflow after the workflow file exists.
path=Path('index.html')
text=path.read_text()
old="""function renderOfficialFallback(entry){const url=entry?.sourceUrl||'';document.getElementById('featured').innerHTML=`<div class=\"official-fallback\"><span class=\"status-pill status-official\">OFFICIAL COUNTY SOURCE</span><h3>${esc(currentCounty)} County Live Results</h3><p>This county's results system is not currently exposing a feed that IRC Media can safely normalize. Rather than show stale or incomplete numbers, use the county's official election-night results directly.</p>${url?`<a class=\"official-btn\" href=\"${esc(url)}\" target=\"_blank\" rel=\"noopener\">View Official ${esc(currentCounty)} County Results</a>`:''}</div>`;document.getElementById('races').innerHTML=renderAggregateOnly();document.getElementById('county-note').innerHTML=`<span class=\"status-pill status-official\">OFFICIAL FALLBACK</span> ${esc(currentCounty)} County is available through its official results system.`}
function renderAggregateOnly(){let out='';if(aggregateIsSafe(statewide)){out+='<section class=\"office-group\"><h3 class=\"office-title\">Florida Statewide Results</h3><div class=\"grid\">'+statewide.races.map(r=>card(r,statewide,'Florida Statewide',true)).join('')+'</div></section>'}else{out+='<section class=\"office-group\"><h3 class=\"office-title\">Florida Statewide Results</h3>'+aggregateMessage('Florida statewide',statewide)+'</section>'}if(aggregateIsSafe(district9)){out+='<section class=\"office-group\"><h3 class=\"office-title\">Congressional District 9 — Districtwide</h3><div class=\"grid\">'+district9.races.map(r=>card(r,district9,'Congressional District 9 — Districtwide',true)).join('')+'</div></section>'}else{out+='<section class=\"office-group\"><h3 class=\"office-title\">Congressional District 9 — Districtwide</h3>'+aggregateMessage('Congressional District 9',district9)+'</section>'}return out}
"""
new="""const OFFICIAL_RESULTS_OVERRIDES={'Okaloosa':'https://www.voteokaloosa.gov/elections/election-results/'};
function countySlice(r){let geo=(r.geography||[]).find(g=>[g.county,g.name,g.id].some(v=>String(v||'')===currentCounty));if(!geo||!geo.votes)return null;let cands=(r.candidates||[]).map(c=>({...c,votes:Number(geo.votes[c.name]??0)}));return {...r,candidates:cands}}
function fallbackCompare(local,aggregate,container,label,title){let dd={...container,countiesIncluded:aggregate.countiesIncluded??container?.countiesIncluded??0,countiesExpected:aggregate.countiesExpected??aggregate.countiesIncluded??container?.countiesExpected??container?.countiesIncluded??0,races:[aggregate]};return`<section class=\"office-group\" id=\"${slug(title)}\"><h3 class=\"office-title\">${esc(title)}</h3><div class=\"compare-grid\">${card(local,{reportingLabel:'Official DOS county total'},currentCounty+' County')}${card(aggregate,dd,label,true)}</div></section>`}
function renderOfficialFallback(entry){const url=OFFICIAL_RESULTS_OVERRIDES[currentCounty]||entry?.sourceUrl||'';document.getElementById('featured').innerHTML=`<div class=\"official-fallback\"><span class=\"status-pill status-official\">OFFICIAL COUNTY SOURCE</span><h3>${esc(currentCounty)} County Local Results</h3><p>IRC Media can still show this county's official Florida DOS totals for statewide and district races below. County-local contests remain linked to the Supervisor of Elections until a safe normalized local feed is available.</p>${url?`<a class=\"official-btn\" href=\"${esc(url)}\" target=\"_blank\" rel=\"noopener\">View Official ${esc(currentCounty)} County Local Results</a>`:''}</div>`;document.getElementById('races').innerHTML=renderAggregateOnly();document.getElementById('county-note').innerHTML=`<span class=\"status-pill status-official\">PARTIAL LOCAL FALLBACK</span> Official DOS county totals are shown below; local-only contests use the county's official results source.`}
function renderAggregateOnly(){let out='';if(aggregateIsSafe(statewide)){(statewide.races||[]).forEach(r=>{let local=countySlice(r);if(local)out+=fallbackCompare(local,r,statewide,'Florida Statewide',officeBase(r.name))})}else out+='<section class=\"office-group\"><h3 class=\"office-title\">Florida Statewide Results</h3>'+aggregateMessage('Florida statewide',statewide)+'</section>';
if(aggregateIsSafe(congressional)&&congressional?.frontendMappingValidation?.status==='passed'){(congressional.races||[]).filter(r=>Array.isArray(r.countyNames)&&r.countyNames.includes(currentCounty)).forEach(r=>{let local=countySlice(r);if(local)out+=fallbackCompare(local,r,congressional,`Congressional District ${r.district} — Districtwide`,`United States Representative — District ${r.district}`)})}
if(aggregateIsSafe(legislative)&&legislative?.frontendMappingValidation?.status==='passed'){(legislative.races||[]).filter(r=>Array.isArray(r.countyNames)&&r.countyNames.includes(currentCounty)).forEach(r=>{let local=countySlice(r);if(local)out+=fallbackCompare(local,r,legislative,`${r.office} District ${r.district} — Districtwide`,`${r.office} — District ${r.district}`)})}
return out||'<div class=\"empty-state\"><h3>Official comparison totals unavailable</h3><p>IRC Media is withholding totals until a complete verified official result is available.</p></div>'}
"""
if old not in text:
    raise SystemExit('Expected fallback renderer block not found; refusing unsafe patch')
text=text.replace(old,new,1)
text=text.replace("report=aggregate?((d.countiesIncluded||0)+' of '+(d.countiesExpected||d.countiesDiscovered||67)+' county feeds included'):(d.precinctsTotal?`${d.precinctsReporting} of ${d.precinctsTotal} precincts`:'Reporting status unavailable')","report=aggregate?((d.countiesIncluded||0)+' of '+(d.countiesExpected||d.countiesDiscovered||67)+' county feeds included'):(d.reportingLabel||(d.precinctsTotal?`${d.precinctsReporting} of ${d.precinctsTotal} precincts`:'Reporting status unavailable'))",1)
path.write_text(text)
print('Applied county-aware fallback v2 renderer')
