from pathlib import Path

p = Path('index.html')
s = p.read_text()

repls = {
    ".leader-badge{display:inline-block;margin-left:8px;padding:3px 7px;border-radius:999px;background:rgba(67,181,129,.18);border:1px solid rgba(67,181,129,.55);color:#8de0b6;font-size:10px;font-weight:900;letter-spacing:.5px;vertical-align:2px}": ".leader-badge{display:inline-block;margin-left:8px;padding:3px 7px;border-radius:999px;background:rgba(67,181,129,.18);border:1px solid rgba(67,181,129,.55);color:#8de0b6;font-size:10px;font-weight:900;letter-spacing:.5px;vertical-align:2px}.incumbent-badge{display:inline-block;margin-left:8px;padding:3px 7px;border-radius:999px;background:rgba(246,196,83,.14);border:1px solid rgba(246,196,83,.55);color:#ffe09a;font-size:10px;font-weight:900;letter-spacing:.5px;vertical-align:2px}",
    '<div class="section-title" id="local-races"><h2 id="race-heading">Indian River County Races</h2>': '<div class="section-title" id="local-races"><h2 id="race-heading">Select Your County</h2>',
    "let currentCounty='Indian River',manifest=null,statewide=null,district9=null,congressional=null,legislative=null;": "let currentCounty=null,manifest=null,statewide=null,district9=null,congressional=null,legislative=null;",
    "function initCounties(){const s=document.getElementById('county-select');s.innerHTML=COUNTIES.map(c=>`<option value=\"${esc(c)}\"${c==='Indian River'?' selected':''}>${esc(c)} County</option>`).join('');s.addEventListener('change',()=>{currentCounty=s.value;loadAll();document.getElementById('local-races').scrollIntoView({behavior:'smooth'})})}": "function initCounties(){const s=document.getElementById('county-select');s.innerHTML='<option value=\"\" selected disabled>Select your county…</option>'+COUNTIES.map(c=>`<option value=\"${esc(c)}\">${esc(c)} County</option>`).join('');s.addEventListener('change',()=>{currentCounty=s.value||null;loadAll();document.getElementById('local-races').scrollIntoView({behavior:'smooth'})})}",
    "<span class=\"name\">${esc(c.name)}</span>${lead?'<span class=\"leader-badge\">LEADING</span>':''}<span class=\"party\">": "<span class=\"name\">${esc(c.name)}</span>${c.incumbent===true?'<span class=\"incumbent-badge\">INCUMBENT</span>':''}${lead?'<span class=\"leader-badge\">LEADING</span>':''}<span class=\"party\">",
    "async function loadAll(){refreshStamp();document.getElementById('race-heading').textContent=currentCounty+' County Races';document.getElementById('hero-copy').textContent=currentCounty+' County results with Florida statewide and districtwide comparisons.';try{await loadManifest();await loadAggregates();": "async function loadAll(){refreshStamp();try{await loadManifest();await loadAggregates();if(!currentCounty){document.getElementById('race-heading').textContent='Select Your County';document.getElementById('hero-copy').textContent='Florida primary results with statewide coverage. Select your county to view local and district races.';document.getElementById('county-note').innerHTML='<span class=\"status-pill status-official\">SELECT A COUNTY</span> Choose your Florida county above to load local races and district comparisons.';document.getElementById('featured').innerHTML='<div class=\"empty-state\"><h3>Choose your county to begin</h3><p>IRC Media covers all 67 Florida counties. Select your county from the menu above to view the races and totals that apply to you.</p></div>';document.getElementById('races').innerHTML=aggregateIsSafe(statewide)?(statewide.races||[]).map(r=>`<section class=\"office-group\" id=\"${slug(officeBase(r.name))}\"><h3 class=\"office-title\">${esc(officeBase(r.name))}</h3><div class=\"grid\">${card(r,statewide,'Florida Statewide',true)}</div></section>`).join(''):aggregateMessage('Florida statewide',statewide);document.getElementById('state-coverage').textContent=aggregateIsSafe(statewide)?'Florida statewide: official/complete':'Florida statewide: WITHHELD pending complete official result';document.getElementById('updated').textContent='Data updated: '+new Intl.DateTimeFormat('en-US',{timeZone:'America/New_York',month:'short',day:'numeric',hour:'numeric',minute:'2-digit',timeZoneName:'short'}).format(new Date(manifest.generatedAt));return}document.getElementById('race-heading').textContent=currentCounty+' County Races';document.getElementById('hero-copy').textContent=currentCounty+' County results with Florida statewide and districtwide comparisons.';",
}

for old, new in repls.items():
    if old not in s:
        raise SystemExit(f'Expected frontend pattern not found: {old[:120]}')
    s = s.replace(old, new, 1)

p.write_text(s)
print('Election Center UX migration applied')
